In [1]:
import numpy as np
import pandas as pd

## 杆单元

In [2]:
def ke(E, A, l):
    Ke = E * A / l * np.array([[1, -1], [-1, 1]])
    return Ke

In [3]:
ke(29.5 * 10**4, 100, 400)

array([[ 73750., -73750.],
       [-73750.,  73750.]])

In [5]:
def kebar(Ke, alpha):
    Te = np.array(
        [[np.cos(alpha), np.sin(alpha), 0, 0], [0, 0, np.cos(alpha), np.sin(alpha)]]
    )
    Ke2 = Te.T @ Ke @ Te
    return Ke2

In [7]:
Ke1 = ke(29.5 * 10**4, 100, 400)

In [21]:
Ke1bar = kebar(Ke1, 0)

In [22]:
Ke1bar

array([[ 73750.,      0., -73750.,      0.],
       [     0.,      0.,      0.,      0.],
       [-73750.,      0.,  73750.,      0.],
       [     0.,      0.,      0.,      0.]])

In [10]:
Ke2 = ke(29.5 * 10**4, 100, 300)

In [14]:
Ke2bar = kebar(Ke2, np.pi / 2)
Ke2bar

array([[ 3.68690947e-28,  6.02118010e-12, -3.68690947e-28,
        -6.02118010e-12],
       [ 6.02118010e-12,  9.83333333e+04, -6.02118010e-12,
        -9.83333333e+04],
       [-3.68690947e-28, -6.02118010e-12,  3.68690947e-28,
         6.02118010e-12],
       [-6.02118010e-12, -9.83333333e+04,  6.02118010e-12,
         9.83333333e+04]])

In [15]:
Ke3 = ke(29.5 * 10**4, 100, 500)

In [16]:
Ke3bar = kebar(Ke3, np.arccos(400 / 500))
Ke3bar

array([[ 37760.,  28320., -37760., -28320.],
       [ 28320.,  21240., -28320., -21240.],
       [-37760., -28320.,  37760.,  28320.],
       [-28320., -21240.,  28320.,  21240.]])

In [17]:
Ke4 = ke(29.5 * 10**4, 100, 400)
Ke4bar = kebar(Ke4, 0)
Ke4bar

array([[ 73750.,      0., -73750.,      0.],
       [     0.,      0.,      0.,      0.],
       [-73750.,      0.,  73750.,      0.],
       [     0.,      0.,      0.,      0.]])

In [48]:
def zuzhuang(Ke1bar, Ke2bar, Ke3bar, Ke4bar):
    a = pd.DataFrame(
        Ke1bar, index=["u1", "v1", "u2", "v2"], columns=["u1", "v1", "u2", "v2"]
    )
    b = pd.DataFrame(
        Ke2bar, index=["u3", "v3", "u2", "v2"], columns=["u3", "v3", "u2", "v2"]
    )
    c = pd.DataFrame(
        Ke3bar, index=["u1", "v1", "u3", "v3"], columns=["u1", "v1", "u3", "v3"]
    )
    d = pd.DataFrame(
        Ke4bar, index=["u4", "v4", "u3", "v3"], columns=["u4", "v4", "u3", "v3"]
    )
    zong = a.add(b, fill_value=0).add(c, fill_value=0).add(d, fill_value=0)
    zongr = zong.replace(np.nan, 0)
    return zongr.reindex(
        index=["u1", "v1", "u2", "v2", "u3", "v3", "u4", "v4"],
        columns=["u1", "v1", "u2", "v2", "u3", "v3", "u4", "v4"],
    )

In [50]:
K = zuzhuang(Ke1bar, Ke2bar, Ke3bar, Ke4bar)

In [53]:
P = np.array([[0, 0, 2 * 10**4, 0, 0, -2.5 * 10**4, 0, 0]]).T

In [58]:
K.iloc[[2, 4, 5], [2, 4, 5]]

u2            u3            v3
u2  7.375000e+04 -3.686909e-28 -6.021180e-12
u3 -3.686909e-28  1.115100e+05  2.832000e+04
v3 -6.021180e-12  2.832000e+04  1.195733e+05

In [61]:
P[[2, 4, 5]]

array([[ 20000.],
       [     0.],
       [-25000.]])

In [63]:
np.linalg.inv(K.iloc[[2, 4, 5], [2, 4, 5]])

array([[ 1.35593220e-05, -1.84504226e-22,  7.26485389e-22],
       [-1.84504226e-22,  9.54174513e-06, -2.25988701e-06],
       [ 7.26485389e-22, -2.25988701e-06,  8.89830508e-06]])

In [64]:
q = np.linalg.inv(K.iloc[[2, 4, 5], [2, 4, 5]]) @ P[[2, 4, 5]]

In [65]:
q

array([[ 0.27118644],
       [ 0.05649718],
       [-0.22245763]])

## 应力计算

In [17]:
sigma = np.array([[1, 0, -4], [0, 3, 0], [-4, 0, 5]])
sigma

array([[ 1,  0, -4],
       [ 0,  3,  0],
       [-4,  0,  5]])

In [18]:
ntest = np.array([0.5, -0.5, 1 / np.sqrt(2)])

array([[ 0.5       , -0.        , -2.82842712]])

In [22]:
def n_yingli_jisuan(sigma_ij, n):
    p = np.dot(sigma_ij, n)
    sigma_n = np.dot(p, n)
    tau = np.sqrt(np.sum(p**2) - sigma_n)
    return sigma_n, tau

In [23]:
n_yingli_jisuan(sigma, ntest)

(np.float64(0.6715728752538097), np.float64(3.059062663017717))

In [ ]:
def zhuyingli(sigma_ij):
    I1 = np.trace(sigma_ij)
    I2 =

## 2Dfem

In [2]:
def area(x1, y1, x2, y2, x3, y3):
    A = 1 / 2 * (x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2))
    return abs(A)

In [12]:
area(0, 0, -2, 0, 1, 2)

2.0

In [3]:
def triangle2d3node_stiffness(E, NU, t, x1, y1, x2, y2, x3, y3, ID):
    """
    This function calculates the stiffness matrix of an element.

    Parameters:
    E (float): Elastic modulus
    NU (float): Poisson's ratio
    t (float): Thickness of the element
    x1, y1, xj, yj, xm, ym (float): Coordinates of nodes i, j, and m
    ID (int): Property indicator for plane problems (1 for plane stress, 2 for plane strain)

    Returns:
    k (numpy.ndarray): Stiffness matrix of the element (6x6)
    """

    # Calculate the area of the triangle
    A = area(x1, y1, x2, y2, x3, y3)

    # Calculate the components of the strain-displacement matrix B
    beta1 = y2 - y3
    beta2 = y3 - y1
    beta3 = y1 - y2
    gamma1 = x3 - x2
    gamma2 = x1 - x3
    gamma3 = x2 - x1

    B = np.array(
        [
            [beta1, 0, beta2, 0, beta3, 0],
            [0, gamma1, 0, gamma2, 0, gamma3],
            [gamma1, beta1, gamma2, beta2, gamma3, beta3],
        ]
    ) / (2 * A)

    # Material property matrix D based on the problem type
    if ID == 1:
        D = (E / (1 - NU**2)) * np.array([[1, NU, 0], [NU, 1, 0], [0, 0, (1 - NU) / 2]])
    elif ID == 2:
        D = (E / ((1 + NU) * (1 - 2 * NU))) * np.array(
            [[1 - NU, NU, 0], [NU, 1 - NU, 0], [0, 0, (1 - 2 * NU) / 2]]
        )

    # Calculate the stiffness matrix k
    k = t * A * np.dot(B.T, np.dot(D, B))

    return k

In [4]:
E = 1e7
NU = 1 / 3
t = 0.1
ID = 1

In [5]:
k1 = triangle2d3node_stiffness(E, NU, t, 2, 1, 1, 0.5, 2, 0, ID)
k2 = triangle2d3node_stiffness(E, NU, t, 2, 1, 0, 1, 1, 0.5, ID)
k3 = triangle2d3node_stiffness(E, NU, t, 0, 1, 0, 0, 1, 0.5, ID)
k4 = triangle2d3node_stiffness(E, NU, t, 2, 0, 1, 0.5, 0, 0, ID)
KK = np.zeros([10, 10])
KK = triangle2d3node_assembly(KK, k1, 1, 5, 2)
KK = triangle2d3node_assembly(KK, k2, 1, 3, 5)
KK = triangle2d3node_assembly(KK, k3, 3, 4, 5)
KK = triangle2d3node_assembly(KK, k4, 2, 5, 4)
with np.printoptions(linewidth=200, suppress=True):
    print(KK)

NameError: name 'triangle2d3node_assembly' is not defined

In [71]:
k23 = KK[0:4, 0:4]
print(k23)
p = np.array([[0, -50000, 0, -50000]])
u = np.linalg.solve(k23, p.T)
u

[[ 6.56250000e+05  3.75000000e+05 -4.68750000e+04  1.16415322e-11]
 [ 3.75000000e+05  1.21875000e+06 -1.16415322e-11 -5.15625000e+05]
 [-4.68750000e+04 -1.16415322e-11  6.56250000e+05 -3.75000000e+05]
 [ 1.16415322e-11 -5.15625000e+05 -3.75000000e+05  1.21875000e+06]]


array([[ 0.05300207],
       [-0.09937888],
       [-0.05300207],
       [-0.09937888]])

In [72]:
k1 = triangle2d3node_stiffness(E, NU, t, 2, 0, 0, 1, 0, 0, ID)
k2 = triangle2d3node_stiffness(E, NU, t, 0, 1, 2, 0, 2, 1, ID)
KK = np.zeros([8, 8])
KK = triangle2d3node_assembly(KK, k1, 2, 3, 4)
KK = triangle2d3node_assembly(KK, k2, 3, 2, 1)
with np.printoptions(linewidth=200, suppress=True):
    print(KK)

[[  656250.   375000.  -375000.  -187500.  -281250.  -187500.        0.        0.]
 [  375000.  1218750.  -187500. -1125000.  -187500.   -93750.        0.        0.]
 [ -375000.  -187500.   656250.        0.        0.   375000.  -281250.  -187500.]
 [ -187500. -1125000.        0.  1218750.   375000.        0.  -187500.   -93750.]
 [ -281250.  -187500.        0.   375000.   656250.        0.  -375000.  -187500.]
 [ -187500.   -93750.   375000.        0.        0.  1218750.  -187500. -1125000.]
 [       0.        0.  -281250.  -187500.  -375000.  -187500.   656250.   375000.]
 [       0.        0.  -187500.   -93750.  -187500. -1125000.   375000.  1218750.]]


In [73]:
k23 = KK[0:4, 0:4]
print(k23)
p = np.array([[0, -50000, 0, -50000]])
u = np.linalg.solve(k23, p.T)
u

[[  656250.   375000.  -375000.  -187500.]
 [  375000.  1218750.  -187500. -1125000.]
 [ -375000.  -187500.   656250.        0.]
 [ -187500. -1125000.        0.  1218750.]]


array([[ 0.18767632],
       [-0.89918337],
       [-0.14966592],
       [-0.84216778]])

In [6]:
k1 = triangle2d3node_stiffness(E, NU, t, 2, 0, 0, 1, 0, 0, ID)
k1

array([[  281250.,        0.,        0.,   187500.,  -281250.,  -187500.],
       [       0.,    93750.,   187500.,        0.,  -187500.,   -93750.],
       [       0.,   187500.,   375000.,        0.,  -375000.,  -187500.],
       [  187500.,        0.,        0.,  1125000.,  -187500., -1125000.],
       [ -281250.,  -187500.,  -375000.,  -187500.,   656250.,   375000.],
       [ -187500.,   -93750.,  -187500., -1125000.,   375000.,  1218750.]])

In [7]:
k2 = triangle2d3node_stiffness(E, NU, t, 0, 1, 2, 0, 2, 1, ID)
k2

array([[  281250.,        0.,        0.,   187500.,  -281250.,  -187500.],
       [       0.,    93750.,   187500.,        0.,  -187500.,   -93750.],
       [       0.,   187500.,   375000.,        0.,  -375000.,  -187500.],
       [  187500.,        0.,        0.,  1125000.,  -187500., -1125000.],
       [ -281250.,  -187500.,  -375000.,  -187500.,   656250.,   375000.],
       [ -187500.,   -93750.,  -187500., -1125000.,   375000.,  1218750.]])

In [6]:
def triangle2d3node_assembly(KK, k, i, j, m):
    """
    该函数将单元刚度矩阵组装到整体刚度矩阵中。

    参数:
    KK (numpy.ndarray): 整体刚度矩阵
    k (numpy.ndarray): 单元刚度矩阵
    i, j, m (int): 单元的节点编号

    返回:
    KK (numpy.ndarray): 更新的整体刚度矩阵
    """

    DOF = [2 * i - 1, 2 * i, 2 * j - 1, 2 * j, 2 * m - 1, 2 * m]

    # 将单元刚度矩阵组装到整体刚度矩阵中
    for n1 in range(6):
        for n2 in range(6):
            KK[DOF[n1] - 1, DOF[n2] - 1] += k[n1, n2]

    return KK

In [18]:
KK = np.zeros([8, 8])
KK = triangle2d3node_assembly(KK, k1, 2, 3, 4)

In [19]:
with np.printoptions(linewidth=200, suppress=True):
    print(KK)

[[       0.        0.        0.        0.        0.        0.        0.        0.]
 [       0.        0.        0.        0.        0.        0.        0.        0.]
 [       0.        0.   281250.        0.        0.   187500.  -281250.  -187500.]
 [       0.        0.        0.    93750.   187500.        0.  -187500.   -93750.]
 [       0.        0.        0.   187500.   375000.        0.  -375000.  -187500.]
 [       0.        0.   187500.        0.        0.  1125000.  -187500. -1125000.]
 [       0.        0.  -281250.  -187500.  -375000.  -187500.   656250.   375000.]
 [       0.        0.  -187500.   -93750.  -187500. -1125000.   375000.  1218750.]]


In [15]:
KK = triangle2d3node_assembly(KK, k2, 3, 2, 1)

In [14]:
with np.printoptions(linewidth=200, suppress=True):
    print(KK)

[[  656250.   375000.  -375000.  -187500.  -281250.  -187500.        0.        0.]
 [  375000.  1218750.  -187500. -1125000.  -187500.   -93750.        0.        0.]
 [ -375000.  -187500.   656250.        0.        0.   375000.  -281250.  -187500.]
 [ -187500. -1125000.        0.  1218750.   375000.        0.  -187500.   -93750.]
 [ -281250.  -187500.        0.   375000.   656250.        0.  -375000.  -187500.]
 [ -187500.   -93750.   375000.        0.        0.  1218750.  -187500. -1125000.]
 [       0.        0.  -281250.  -187500.  -375000.  -187500.   656250.   375000.]
 [       0.        0.  -187500.   -93750.  -187500. -1125000.   375000.  1218750.]]


In [17]:
K_1414 = KK[0:4, 0:4]
K_1414

array([[  656250.,   375000.,  -375000.,  -187500.],
       [  375000.,  1218750.,  -187500., -1125000.],
       [ -375000.,  -187500.,   656250.,        0.],
       [ -187500., -1125000.,        0.,  1218750.]])

In [20]:
p = np.array([[0, -50000, 0, -50000]])

In [22]:
u = np.linalg.solve(K_1414, p.T)
u

array([[ 0.18767632],
       [-0.89918337],
       [-0.14966592],
       [-0.84216778]])

In [25]:
U = np.vstack((u.T, np.zeros(4))).reshape(8, 1)
U

array([[ 0.18767632],
       [-0.89918337],
       [-0.14966592],
       [-0.84216778],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ]])

In [26]:
P = KK @ U
P

array([[      0.        ],
       [ -50000.        ],
       [      0.        ],
       [ -50000.        ],
       [-200000.        ],
       [  -7015.59020045],
       [ 200000.        ],
       [ 107015.59020045]])

In [6]:
def triangle2d3node_stress(E, NU, xi, yi, xj, yj, xm, ym, u, ID):
    """
    该函数计算单元的应力。

    参数:
    E (float): 弹性模量
    NU (float): 泊松比
    xi, yi, xj, yj, xm, ym (float): 节点i、j、m的坐标
    u (numpy.ndarray): 单元的位移列阵 (6x1)
    ID (int): 平面问题性质指标参数 (1为平面应力，2为平面应变)

    返回:
    stress (numpy.ndarray): 单元的应力 (3x1)，包含Sx, Sy, Sxy
    """

    import numpy as np

    # 计算三角形面积
    A = area(x1, y1, x2, y2, x3, y3)

    # 计算应变-位移矩阵B的各分量
    betai = yj - ym
    betaj = ym - yi
    betam = yi - yj
    gammai = xm - xj
    gammaj = xi - xm
    gammam = xj - xi

    B = np.array(
        [
            [betai, 0, betaj, 0, betam, 0],
            [0, gammai, 0, gammaj, 0, gammam],
            [gammai, betai, gammaj, betaj, gammam, betam],
        ]
    ) / (2 * A)

    # 根据问题类型计算材料属性矩阵D
    if ID == 1:
        D = (E / (1 - NU**2)) * np.array([[1, NU, 0], [NU, 1, 0], [0, 0, (1 - NU) / 2]])
    elif ID == 2:
        D = (E / ((1 + NU) * (1 - 2 * NU))) * np.array(
            [[1 - NU, NU, 0], [NU, 1 - NU, 0], [0, 0, (1 - 2 * NU) / 2]]
        )

    # 计算应力
    stress = np.dot(D, np.dot(B, u))

    return stress

In [7]:
import meshio

In [88]:
# 读取 .msh 文件
file_path = "/mnt/c/Users/Yuxua/Desktop/TODO/simplex2y1.msh"
mesh = meshio.read(file_path)

# 打印节点
print("Points:")
print(mesh.points)

# 打印单元
print("Cells:")
for cell_block in mesh.cells:
    cell_type = cell_block.type
    cell_data = cell_block.data
    print(f"Cell type: {cell_type}")
    print(cell_data)


Points:
[[0.  0.  0. ]
 [2.  0.  0. ]
 [2.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.5 0. ]]
Cells:
Cell type: vertex
[[0]]
Cell type: vertex
[[1]]
Cell type: vertex
[[2]]
Cell type: vertex
[[3]]
Cell type: line
[[0 1]]
Cell type: line
[[1 2]]
Cell type: line
[[2 3]]
Cell type: line
[[3 0]]
Cell type: triangle
[[0 4 3]
 [2 4 1]
 [1 4 0]
 [3 4 2]]


In [89]:
mesh.points

array([[0. , 0. , 0. ],
       [2. , 0. , 0. ],
       [2. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0.5, 0. ]])

In [90]:
mesh.cells_dict["triangle"]

array([[0, 4, 3],
       [2, 4, 1],
       [1, 4, 0],
       [3, 4, 2]])

In [91]:
KK = np.zeros([10, 10])
for ncell in range(4):
    nodes = mesh.cells_dict["triangle"][ncell]
    loca = mesh.points[nodes][:, 0:2]
    locaf = loca.flatten()
    ki = triangle2d3node_stiffness(
        E, NU, t, locaf[0], locaf[1], locaf[2], locaf[3], locaf[4], locaf[5], ID
    )
    with np.printoptions(linewidth=200, suppress=True):
        print(ki)
    KK = triangle2d3node_assembly(KK, ki, nodes[0] + 1, nodes[1] + 1, nodes[2] + 1)

[[ 328125.  187500. -281250. -187500.  -46875.       0.]
 [ 187500.  609375. -187500.  -93750.      -0. -515625.]
 [-281250. -187500.  562500.       0. -281250.  187500.]
 [-187500.  -93750.       0.  187500.  187500.  -93750.]
 [ -46875.      -0. -281250.  187500.  328125. -187500.]
 [      0. -515625.  187500.  -93750. -187500.  609375.]]
[[ 328125.  187500. -281250. -187500.  -46875.       0.]
 [ 187500.  609375. -187500.  -93750.      -0. -515625.]
 [-281250. -187500.  562500.       0. -281250.  187500.]
 [-187500.  -93750.       0.  187500.  187500.  -93750.]
 [ -46875.      -0. -281250.  187500.  328125. -187500.]
 [      0. -515625.  187500.  -93750. -187500.  609375.]]
[[  328125.  -187500.  -375000.   187500.    46875.        0.]
 [ -187500.   609375.   187500. -1125000.       -0.   515625.]
 [ -375000.   187500.   750000.        0.  -375000.  -187500.]
 [  187500. -1125000.        0.  2250000.  -187500. -1125000.]
 [   46875.       -0.  -375000.  -187500.   328125.   187500.]

In [92]:
with np.printoptions(linewidth=200, suppress=True):
    print(KK)

[[  656250.   375000.    46875.       -0.        0.        0.   -46875.        0.  -656250.  -375000.]
 [  375000.  1218750.        0.   515625.        0.        0.       -0.  -515625.  -375000. -1218750.]
 [   46875.        0.   656250.  -375000.   -46875.       -0.        0.        0.  -656250.   375000.]
 [      -0.   515625.  -375000.  1218750.        0.  -515625.        0.        0.   375000. -1218750.]
 [       0.        0.   -46875.        0.   656250.   375000.    46875.       -0.  -656250.  -375000.]
 [       0.        0.       -0.  -515625.   375000.  1218750.        0.   515625.  -375000. -1218750.]
 [  -46875.       -0.        0.        0.    46875.        0.   656250.  -375000.  -656250.   375000.]
 [       0.  -515625.        0.        0.       -0.   515625.  -375000.  1218750.   375000. -1218750.]
 [ -656250.  -375000.  -656250.   375000.  -656250.  -375000.  -656250.   375000.  2625000.        0.]
 [ -375000. -1218750.   375000. -1218750.  -375000. -1218750.   375000. -

In [93]:
k23 = KK[2:6, 2:6]
print(k23)
p = np.array([[0, -50000, 0, -50000]])
u = np.linalg.solve(k23, p.T)
u

[[ 6.56250000e+05 -3.75000000e+05 -4.68750000e+04 -1.16415322e-11]
 [-3.75000000e+05  1.21875000e+06  1.16415322e-11 -5.15625000e+05]
 [-4.68750000e+04  1.16415322e-11  6.56250000e+05  3.75000000e+05]
 [-1.16415322e-11 -5.15625000e+05  3.75000000e+05  1.21875000e+06]]


array([[-0.05300207],
       [-0.09937888],
       [ 0.05300207],
       [-0.09937888]])

In [101]:
U = np.array(
    [
        [0],
        [0],
        [-0.05300207],
        [-0.09937888],
        [0.05300207],
        [-0.09937888],
        [0],
        [0],
        [0],
        [0],
    ]
)
U

array([[ 0.        ],
       [ 0.        ],
       [-0.05300207],
       [-0.09937888],
       [ 0.05300207],
       [-0.09937888],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ]])

In [102]:
P = KK @ U
P

array([[-2.48447203e+03],
       [-5.12422350e+04],
       [-4.68749997e-04],
       [-4.99999988e+04],
       [ 4.68749997e-04],
       [-4.99999988e+04],
       [ 2.48447203e+03],
       [-5.12422350e+04],
       [ 0.00000000e+00],
       [ 2.02484468e+05]])

### 复杂网络

In [ ]:
file_path = "/mnt/c/Users/Yuxua/Desktop/TODO/compx2y1.msh"
mesh = meshio.read(file_path)
# mesh.points.shape
# mesh.cells_dict["triangle"].shape

In [15]:
KK = np.zeros([mesh.points.shape[0]*2, mesh.points.shape[0]*2])
for ncell in range(mesh.cells_dict["triangle"].shape[0]):
    nodes = mesh.cells_dict['triangle'][ncell]
    loca = mesh.points[nodes][:, 0:2]
    locaf = loca.flatten()
    ki = triangle2d3node_stiffness(E, NU, t, locaf[0], locaf[1], locaf[2], locaf[3], locaf[4], locaf[5], ID)
    KK = triangle2d3node_assembly(KK, ki, nodes[0]+1, nodes[1]+1, nodes[2]+1)

# 边界条件设置
rows_to_select = [2,3,4,5,24,25,26,27,28,29,30,31]
cols_to_select = [2,3,4,5,24,25,26,27,28,29,30,31]

k23 = KK[np.ix_(rows_to_select, cols_to_select)]

p = np.array([[0, -100000/6, 0, -100000/6, 0, -100000/6, 0, -100000/6, 0, -100000/6, 0, -100000/6]])
u = np.linalg.solve(k23, p.T)
u.T

array([[-0.02686892, -0.06156042,  0.02591514, -0.06191906, -0.00487682,
        -0.04422332,  0.00378375, -0.03490036, -0.00385267, -0.03504489,
         0.00563597, -0.04480833]])

## 平板圆孔

In [9]:
file_path = "/mnt/c/Users/Yuxua/Desktop/TODO/hole.msh"
mesh = meshio.read(file_path)

# 打印节点
print("Points:")
print(mesh.points)

# 打印单元
print("Cells:")
for cell_block in mesh.cells:
    cell_type = cell_block.type
    cell_data = cell_block.data
    print(f"Cell type: {cell_type}")
    print(cell_data)


Points:
[[0.         0.         0.        ]
 [1.         0.         0.        ]
 [0.         1.         0.        ]
 ...
 [0.91436174 0.96285912 0.        ]
 [0.69817391 0.47405362 0.        ]
 [0.58480084 0.30063859 0.        ]]
Cells:
Cell type: vertex
[[0]]
Cell type: vertex
[[1]]
Cell type: vertex
[[2]]
Cell type: vertex
[[3]]
Cell type: vertex
[[4]]
Cell type: line
[[ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]
 [10 11]
 [11 12]
 [12 13]
 [13 14]
 [14  4]]
Cell type: line
[[ 0 15]
 [15 16]
 [16 17]
 [17 18]
 [18 19]
 [19 20]
 [20 21]
 [21 22]
 [22 23]
 [23 24]
 [24 25]
 [25 26]
 [26 27]
 [27 28]
 [28 29]
 [29 30]
 [30  1]]
Cell type: line
[[ 2 31]
 [31 32]
 [32 33]
 [33 34]
 [34 35]
 [35 36]
 [36 37]
 [37 38]
 [38 39]
 [39 40]
 [40 41]
 [41 42]
 [42 43]
 [43 44]
 [44 45]
 [45 46]
 [46  0]]
Cell type: line
[[ 1 47]
 [47 48]
 [48 49]
 [49 50]
 [50 51]
 [51 52]
 [52 53]
 [53 54]
 [54 55]
 [55 56]
 [56 57]
 [57 58]
 [58 59]
 [59 60]
 [60 61]
 [61 62]
 [62  3]]
Cell type: line


In [10]:
mesh.points.shape

(421, 3)

In [11]:
mesh.cells_dict["triangle"].shape

(763, 3)

In [ ]:
KK = np.zeros([mesh.points.shape[0] * 2, mesh.points.shape[0] * 2])
for ncell in range(mesh.cells_dict["triangle"].shape[0]):
    nodes = mesh.cells_dict["triangle"][ncell]
    loca = mesh.points[nodes][:, 0:2]
    locaf = loca.flatten()
    ki = triangle2d3node_stiffness(
        E, NU, t, locaf[0], locaf[1], locaf[2], locaf[3], locaf[4], locaf[5], ID
    )
    KK = triangle2d3node_assembly(KK, ki, nodes[0] + 1, nodes[1] + 1, nodes[2] + 1)

# 定义要选取的行和列的索引
rows_to_select = [2, 3, 4, 5, 24, 25, 26, 27, 28, 29, 30, 31]
cols_to_select = [2, 3, 4, 5, 24, 25, 26, 27, 28, 29, 30, 31]

# 选取特定行和列的数据
k23 = KK[np.ix_(rows_to_select, cols_to_select)]
print(k23)
p = np.array(
    [
        [
            0,
            -100000 / 6,
            0,
            -100000 / 6,
            0,
            -100000 / 6,
            0,
            -100000 / 6,
            0,
            -100000 / 6,
            0,
            -100000 / 6,
        ]
    ]
)
u = np.linalg.solve(k23, p.T)
u